description: Stack to setup an ECS Fargate Cluster
name: stackspot-aws-ecs-cluster
display-name: stackspot-aws-ecs-cluster
picture: stack.png
category: SRE # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - github
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies 
  - Terraform
  - AWS ECS/Fargate
about: docs/about.md
use-cases:
  - title: Use Case Title
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml