name: Terraform Apply

on:
  push:
    branches: [ main ]

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Terraform Code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
        {% raw %}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        {% endraw %}
          aws-region: us-east-1
      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init
      - name: Plan Terraform
        run: |
          cd terraform
          terraform plan
      - name: Apply Terraform
        run: |
          cd terraform
          terraform apply -auto-approve
